### ISSUE TITLE
No 'route_distances' module found 

### ISSUE THREAD

**Issue by m-mokaya** [MolecularAI/route-distances#1]
I have updated to the latest aizynthfinder version (3.0.0) through an upstream fetch. However, when I try and use the AiZynthFinder python interface I get the error:

ModuleNotFoundError: No module named 'route_distances'

I believe the new route distance tool is included in the latest AiZ release. Is the issue that I have not installed it correctly? Do I need to do anything for it to work? Thank you for your help. 

Best wishes.

**Comment by SGenheden** [comment]
Thank you for your feedback.

I am unsure exactly how you install `aizynthfinder` in the first place. But if the `route_distance` package was not installed for some reason you can do it manually:

* Activate your conda environment: `conda activate ...`
* Execute `python -m pip install https://github.com/MolecularAI/route-distances/archive/refs/tags/v0.2.0.tar.gz`

and it will install the latest version of `route_distances` package.

**Comment by SGenheden** [comment]
Will close this due to inactivity. If there is still an issue, let me know.
